### ISSUE TITLE
Incorrect description on plugin page.

### ISSUE THREAD

**Issue by stahor** [raulanatol/camaleon-google_analytic#1]
from http://camaleon.tuzitio.com/store/plugins/google_analytic

> Add this in your Gemfile:
> `gem 'camaleon_google_analytics'`

It does not work. The correct gem name is camaleon_google_analytic

**Comment by raulanatol** [comment]
Sorry @stahor for the delay. The notification of this issue was lost in the inbox.
It's fixed now.
Thanks
Regards
