### ISSUE TITLE
Won't install on Rails 5

### ISSUE THREAD

**Issue by brian-kephart** [raulanatol/camaleon-google_analytic#2]
Is a compatibility update in the works?

**Comment by raulanatol** [comment]
Hi @briank-musichouse!

It's not in my plans migrate to Rails 5 now.
What error do you have?

Regards

**Comment by brian-kephart** [comment]
The gemspec requires Rails ~> '4.2' so bundle install failed with Rails 5.

I changed the dependency in my fork to Rails >= '4.2' and it seems to work
just fine.

Brian Kephart
Tech Manager
Music House School of Music http://www.musichouseschool.com
(913) 562-4112 x2

12715 W 87th St Pkwy
Lenexa, KS 66215

7465 W 161st Street
Overland Park, KS 66085

**Comment by raulanatol** [comment]
Done!

Thanks @briank-musichouse
